<?php

/**
 * @file
 * Helper functions for the NPR API module.
 */

/**
 * Implements hook_cron().
 *
 * @see \Drupal\npr_pull\Plugin\QueueWorker\StoryQueueWorker
 *
 * @throws \Exception
 */
function npr_pull_cron(): void {
  /** @var \Drupal\Core\Config\ConfigFactoryInterface $config_factory */
  $config_factory = \Drupal::configFactory();
  $config = $config_factory->get('npr_pull.settings');

  $request_time = \Drupal::time()->getRequestTime();
  $now = new DateTime("@{$request_time}");

  if ($config->get('queue_interval')) {
    /** @var \Drupal\npr_pull\NprPullClient $nprPullClient */
    $nprPullClient = Drupal::service('npr_pull.client');

    $interval = (int) $config->get('queue_interval');
    $diff = $now->getTimestamp() - $nprPullClient->getLastUpdateTime()->getTimestamp();

    if ($diff > $interval) {
      _npr_pull_story_update_queue();
    }
  }
}

/**
 * Executes the Story queue update operation.
 *
 * @throws \Exception
 */
function _npr_pull_story_update_queue() {
  /** @var \Drupal\npr_pull\NprPullClient $nprPullClient */
  $nprPullClient = Drupal::service('npr_pull.client');
  $nprPullClient->updateQueue();
}
