<?php

/**
 * Implements hook_node_info().
 */
function npr_api_story_node_info() {
  return array(
    'npr_story' => array(
      'name' => t('NPR Story'),
      'base' => 'npr_story',
      'description' => t('NPR Story.'),
      'locked' => TRUE,
      'title_label' => 'Headline',
    ),
  );
}

/**
 * Implements hook_form().
 */
function npr_story_form($node, $form_state) {
  return node_content_form($node, $form_state);
}

/**
 * Implements hook_field_formatter_info().
 *
 *
 * @see npr_api_story_field_formatter_view()
 */
function npr_api_story_field_formatter_info() {
  return array(
    'npr_audio_mp3' => array(
      'label' => t('Basic MP3 player'),
      'field types' => array('text'),
    ),
  );
}

/**
 * Implements hook_field_formatter_view().
 *
 * @see npr_api_story_field_formatter_info()
 */
function npr_api_story_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();

  switch ($display['type']) {
    case 'npr_audio_mp3':
      foreach ($items as $delta => $item) {
        $element[$delta] = array(
          '#type' => 'html_tag',
          '#tag' => 'embed',
          '#attributes' => array(
            'src' => $item['value'],
            'type' => 'audio/mpeg',
            'autostart' => 'FALSE',
          ),
          '#value' => '',
        );
      }
      break;
  }

  return $element;
}

function npr_api_story_preprocess_node(&$variables) {
  if ($variables['node']->type == 'npr_story') {
    drupal_add_css(drupal_get_path('module', 'npr_api_story') . '/css/npr_api_story.css');
  }
}